In [1]:
from data.Chexpert import Chexpert
from modules.ChexpertModule import ChexpertDataModule
#from modules.ChexpertModule import ChexpertDataModule
from utils.environment_settings import env_settings
from utils.utils import *
from utils._prepare_data import DataHandler
import matplotlib.pyplot as plt
from torch.utils.data import random_split
import torchvision
import numpy as np

/home/guests/usr_mlmi/.conda/envs/ark_biovil/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
params = read_config(env_settings.CONFIG)

In [3]:
processor = DataHandler(opt=params["dataset"])

['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia', 'Pneumothorax']
Index(['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema',
       'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity',
       'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia',
       'Pneumothorax'],
      dtype='object')
Created paired dataset.


In [4]:
chexpert_data_module = ChexpertDataModule(opt=params['dataset'], processor=processor)

In [5]:
chexpert_data_module.setup()

In [6]:
train_dataloader = chexpert_data_module.train_dataloader()

In [7]:
val_dataloader = chexpert_data_module.val_dataloader()

In [8]:
test_dataloader = chexpert_data_module.test_dataloader()

In [9]:
accumulated_batches = []

In [13]:
## TEST ###
#dataiter = iter(train_dataloader)
first_batch = next(dataiter)
# Extract images and labels
images, labels = first_batch['target'], first_batch['report']

In [14]:
labels

tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
       

In [15]:
accumulated_batches.append(labels)

In [16]:
accumulated_batches

[tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0

In [17]:
import torch
torch.cat(accumulated_batches, dim=0)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
        

In [18]:
outputs = torch.sigmoid(torch.cat(accumulated_batches, dim=0))

In [19]:
outputs

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311, 0.5000,
         0.7311, 0.5000, 0.7311, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.7311,
         0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.7311, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.7311, 0.5000, 0.5000, 0.5000],
        [0.5000,

In [20]:
from utils.post_processing import post_process

In [21]:
a,b = post_process(outputs, 'zeros', params['dataset']['chexpert_labels'])

In [22]:
a

{'combinations': {'No Finding': 0.7222222222222222,
  'Lung Opacity': 0.1111111111111111,
  'Lung Opacity, Pleural Effusion, Pneumonia': 0.05555555555555555,
  'Cardiomegaly, Pleural Effusion': 0.05555555555555555,
  'Edema': 0.05555555555555555,
  'Atelectasis': 0.1111111111111111,
  'Cardiomegaly, Edema': 0.05555555555555555,
  'Cardiomegaly, Edema, Pleural Effusion': 0.05555555555555555,
  'Edema, Pleural Effusion': 0.05555555555555555,
  'Lung Opacity, Pleural Effusion': 0.05555555555555555,
  'Consolidation, Pleural Effusion': 0.05555555555555555,
  'Atelectasis, Cardiomegaly, Pleural Effusion, Pneumothorax': 0.05555555555555555,
  'Atelectasis, Enlarged Cardiomediastinum, Lung Opacity, Pleural Other': 0.05555555555555555,
  'Fracture, Pneumonia': 0.05555555555555555,
  'Atelectasis, Edema, Pleural Effusion, Pneumonia': 0.05555555555555555,
  'Pneumothorax': 0.05555555555555555,
  'Consolidation, Pneumonia': 0.05555555555555555,
  'Atelectasis, Cardiomegaly, Pneumothorax': 0.05555

In [25]:
b['distributions'] + 1e-10

tensor([3.2962e-01, 2.4779e-02, 4.0321e-03, 8.5073e-03, 2.0751e-02, 3.0204e-02,
        1.5484e-02, 1.2712e-02, 1.2692e-02, 8.2956e-03, 2.6881e-03, 8.7633e-04,
        3.9386e-05, 1.1816e-04, 6.8433e-04, 1.4898e-02, 3.6530e-03, 9.6495e-04])

In [ ]:
# Function to show a batch of images
def imshow(img):
    img = img / 2 + 0.5  # unnormalize if you used normalization like mean=[0.485, 0.456, 0.406] and std=[0.229, 0.224, 0.225]
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

# Set a larger figure size
plt.figure(figsize=(50, 50))  # You can adjust these dimensions as needed

# Adjust the number of images per row in the grid
# 'images' is a batch of your images
grid_img = torchvision.utils.make_grid(images, nrow=5)  # Adjust 'nrow' based on your preference

imshow(grid_img)

# Show the plot
plt.show()
